// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: packages/bridge/proto/workflow.proto

package bridgepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowBridge_ListWorkflows_FullMethodName = "/macos.bridge.v1.WorkflowBridge/ListWorkflows"
	WorkflowBridge_RunWorkflow_FullMethodName   = "/macos.bridge.v1.WorkflowBridge/RunWorkflow"
	WorkflowBridge_ListRuns_FullMethodName      = "/macos.bridge.v1.WorkflowBridge/ListRuns"
	WorkflowBridge_RunLog_FullMethodName        = "/macos.bridge.v1.WorkflowBridge/RunLog"
)

// WorkflowBridgeClient is the client API for WorkflowBridge service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowBridgeClient interface {
	ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error)
	RunWorkflow(ctx context.Context, in *RunWorkflowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowEvent], error)
	ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error)
	RunLog(ctx context.Context, in *RunLogRequest, opts ...grpc.CallOption) (*RunLogResponse, error)
}

type workflowBridgeClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowBridgeClient(cc grpc.ClientConnInterface) WorkflowBridgeClient {
	return &workflowBridgeClient{cc}
}

func (c *workflowBridgeClient) ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkflowsResponse)
	err := c.cc.Invoke(ctx, WorkflowBridge_ListWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowBridgeClient) RunWorkflow(ctx context.Context, in *RunWorkflowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkflowBridge_ServiceDesc.Streams[0], WorkflowBridge_RunWorkflow_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RunWorkflowRequest, WorkflowEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkflowBridge_RunWorkflowClient = grpc.ServerStreamingClient[WorkflowEvent]

func (c *workflowBridgeClient) ListRuns(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (*ListRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRunsResponse)
	err := c.cc.Invoke(ctx, WorkflowBridge_ListRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowBridgeClient) RunLog(ctx context.Context, in *RunLogRequest, opts ...grpc.CallOption) (*RunLogResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunLogResponse)
	err := c.cc.Invoke(ctx, WorkflowBridge_RunLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowBridgeServer is the server API for WorkflowBridge service.
// All implementations must embed UnimplementedWorkflowBridgeServer
// for forward compatibility.
type WorkflowBridgeServer interface {
	ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error)
	RunWorkflow(*RunWorkflowRequest, grpc.ServerStreamingServer[WorkflowEvent]) error
	ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error)
	RunLog(context.Context, *RunLogRequest) (*RunLogResponse, error)
	mustEmbedUnimplementedWorkflowBridgeServer()
}

// UnimplementedWorkflowBridgeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowBridgeServer struct{}

func (UnimplementedWorkflowBridgeServer) ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkflows not implemented")
}
func (UnimplementedWorkflowBridgeServer) RunWorkflow(*RunWorkflowRequest, grpc.ServerStreamingServer[WorkflowEvent]) error {
	return status.Error(codes.Unimplemented, "method RunWorkflow not implemented")
}
func (UnimplementedWorkflowBridgeServer) ListRuns(context.Context, *ListRunsRequest) (*ListRunsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRuns not implemented")
}
func (UnimplementedWorkflowBridgeServer) RunLog(context.Context, *RunLogRequest) (*RunLogResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunLog not implemented")
}
func (UnimplementedWorkflowBridgeServer) mustEmbedUnimplementedWorkflowBridgeServer() {}
func (UnimplementedWorkflowBridgeServer) testEmbeddedByValue()                        {}

// UnsafeWorkflowBridgeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowBridgeServer will
// result in compilation errors.
type UnsafeWorkflowBridgeServer interface {
	mustEmbedUnimplementedWorkflowBridgeServer()
}

func RegisterWorkflowBridgeServer(s grpc.ServiceRegistrar, srv WorkflowBridgeServer) {
	// If the following call panics, it indicates UnimplementedWorkflowBridgeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowBridge_ServiceDesc, srv)
}

func _WorkflowBridge_ListWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowBridgeServer).ListWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowBridge_ListWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowBridgeServer).ListWorkflows(ctx, req.(*ListWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowBridge_RunWorkflow_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RunWorkflowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkflowBridgeServer).RunWorkflow(m, &grpc.GenericServerStream[RunWorkflowRequest, WorkflowEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkflowBridge_RunWorkflowServer = grpc.ServerStreamingServer[WorkflowEvent]

func _WorkflowBridge_ListRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRunsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowBridgeServer).ListRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowBridge_ListRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowBridgeServer).ListRuns(ctx, req.(*ListRunsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowBridge_RunLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowBridgeServer).RunLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowBridge_RunLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowBridgeServer).RunLog(ctx, req.(*RunLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowBridge_ServiceDesc is the grpc.ServiceDesc for WorkflowBridge service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowBridge_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "macos.bridge.v1.WorkflowBridge",
	HandlerType: (*WorkflowBridgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListWorkflows",
			Handler:    _WorkflowBridge_ListWorkflows_Handler,
		},
		{
			MethodName: "ListRuns",
			Handler:    _WorkflowBridge_ListRuns_Handler,
		},
		{
			MethodName: "RunLog",
			Handler:    _WorkflowBridge_RunLog_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunWorkflow",
			Handler:       _WorkflowBridge_RunWorkflow_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "packages/bridge/proto/workflow.proto",
}
