// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: packages/bridge/proto/workflow.proto

package bridgepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListWorkflowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsRequest) Reset() {
	*x = ListWorkflowsRequest{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsRequest) ProtoMessage() {}

func (x *ListWorkflowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsRequest.ProtoReflect.Descriptor instead.
func (*ListWorkflowsRequest) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{0}
}

type ListWorkflowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workflows     []*Workflow            `protobuf:"bytes,1,rep,name=workflows,proto3" json:"workflows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWorkflowsResponse) Reset() {
	*x = ListWorkflowsResponse{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWorkflowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWorkflowsResponse) ProtoMessage() {}

func (x *ListWorkflowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWorkflowsResponse.ProtoReflect.Descriptor instead.
func (*ListWorkflowsResponse) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *ListWorkflowsResponse) GetWorkflows() []*Workflow {
	if x != nil {
		return x.Workflows
	}
	return nil
}

type Workflow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ChangesMac    string                 `protobuf:"bytes,4,opt,name=changes_mac,json=changesMac,proto3" json:"changes_mac,omitempty"`
	Phases        []*Phase               `protobuf:"bytes,5,rep,name=phases,proto3" json:"phases,omitempty"`
	Confirmation  *Confirmation          `protobuf:"bytes,6,opt,name=confirmation,proto3" json:"confirmation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *Workflow) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Workflow) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workflow) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Workflow) GetChangesMac() string {
	if x != nil {
		return x.ChangesMac
	}
	return ""
}

func (x *Workflow) GetPhases() []*Phase {
	if x != nil {
		return x.Phases
	}
	return nil
}

func (x *Workflow) GetConfirmation() *Confirmation {
	if x != nil {
		return x.Confirmation
	}
	return nil
}

type Phase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Phase) Reset() {
	*x = Phase{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Phase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Phase) ProtoMessage() {}

func (x *Phase) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Phase.ProtoReflect.Descriptor instead.
func (*Phase) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *Phase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Phase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Phase) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type Confirmation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Options       []*ConfirmationOption  `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Confirmation) Reset() {
	*x = Confirmation{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Confirmation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Confirmation) ProtoMessage() {}

func (x *Confirmation) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Confirmation.ProtoReflect.Descriptor instead.
func (*Confirmation) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *Confirmation) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Confirmation) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Confirmation) GetOptions() []*ConfirmationOption {
	if x != nil {
		return x.Options
	}
	return nil
}

type ConfirmationOption struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Continue      bool                   `protobuf:"varint,4,opt,name=continue,proto3" json:"continue,omitempty"`
	Back          bool                   `protobuf:"varint,5,opt,name=back,proto3" json:"back,omitempty"`
	Phases        []*Phase               `protobuf:"bytes,6,rep,name=phases,proto3" json:"phases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmationOption) Reset() {
	*x = ConfirmationOption{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmationOption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmationOption) ProtoMessage() {}

func (x *ConfirmationOption) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmationOption.ProtoReflect.Descriptor instead.
func (*ConfirmationOption) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *ConfirmationOption) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmationOption) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ConfirmationOption) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ConfirmationOption) GetContinue() bool {
	if x != nil {
		return x.Continue
	}
	return false
}

func (x *ConfirmationOption) GetBack() bool {
	if x != nil {
		return x.Back
	}
	return false
}

func (x *ConfirmationOption) GetPhases() []*Phase {
	if x != nil {
		return x.Phases
	}
	return nil
}

type RunWorkflowRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId           string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	ConfirmationOptionId string                 `protobuf:"bytes,2,opt,name=confirmation_option_id,json=confirmationOptionId,proto3" json:"confirmation_option_id,omitempty"`
	EnabledPhaseIds      []string               `protobuf:"bytes,3,rep,name=enabled_phase_ids,json=enabledPhaseIds,proto3" json:"enabled_phase_ids,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RunWorkflowRequest) Reset() {
	*x = RunWorkflowRequest{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunWorkflowRequest) ProtoMessage() {}

func (x *RunWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunWorkflowRequest.ProtoReflect.Descriptor instead.
func (*RunWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *RunWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RunWorkflowRequest) GetConfirmationOptionId() string {
	if x != nil {
		return x.ConfirmationOptionId
	}
	return ""
}

func (x *RunWorkflowRequest) GetEnabledPhaseIds() []string {
	if x != nil {
		return x.EnabledPhaseIds
	}
	return nil
}

type WorkflowEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	PhaseId       string                 `protobuf:"bytes,5,opt,name=phase_id,json=phaseId,proto3" json:"phase_id,omitempty"`
	PhaseName     string                 `protobuf:"bytes,6,opt,name=phase_name,json=phaseName,proto3" json:"phase_name,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,8,opt,name=message,proto3" json:"message,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowEvent) Reset() {
	*x = WorkflowEvent{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowEvent) ProtoMessage() {}

func (x *WorkflowEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowEvent.ProtoReflect.Descriptor instead.
func (*WorkflowEvent) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *WorkflowEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WorkflowEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WorkflowEvent) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *WorkflowEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *WorkflowEvent) GetPhaseId() string {
	if x != nil {
		return x.PhaseId
	}
	return ""
}

func (x *WorkflowEvent) GetPhaseName() string {
	if x != nil {
		return x.PhaseName
	}
	return ""
}

func (x *WorkflowEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *WorkflowEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ListRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsRequest) Reset() {
	*x = ListRunsRequest{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsRequest) ProtoMessage() {}

func (x *ListRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsRequest.ProtoReflect.Descriptor instead.
func (*ListRunsRequest) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *ListRunsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListRunsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Runs          []*RunSummary          `protobuf:"bytes,1,rep,name=runs,proto3" json:"runs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRunsResponse) Reset() {
	*x = ListRunsResponse{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRunsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRunsResponse) ProtoMessage() {}

func (x *ListRunsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRunsResponse.ProtoReflect.Descriptor instead.
func (*ListRunsResponse) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *ListRunsResponse) GetRuns() []*RunSummary {
	if x != nil {
		return x.Runs
	}
	return nil
}

type RunSummary struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId              string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	WorkflowName            string                 `protobuf:"bytes,3,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	ConfirmationOptionId    string                 `protobuf:"bytes,4,opt,name=confirmation_option_id,json=confirmationOptionId,proto3" json:"confirmation_option_id,omitempty"`
	ConfirmationOptionLabel string                 `protobuf:"bytes,5,opt,name=confirmation_option_label,json=confirmationOptionLabel,proto3" json:"confirmation_option_label,omitempty"`
	Mode                    string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"`
	Status                  string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt               string                 `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt             string                 `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	ErrorMessage            string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RunSummary) Reset() {
	*x = RunSummary{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSummary) ProtoMessage() {}

func (x *RunSummary) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSummary.ProtoReflect.Descriptor instead.
func (*RunSummary) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *RunSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RunSummary) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *RunSummary) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *RunSummary) GetConfirmationOptionId() string {
	if x != nil {
		return x.ConfirmationOptionId
	}
	return ""
}

func (x *RunSummary) GetConfirmationOptionLabel() string {
	if x != nil {
		return x.ConfirmationOptionLabel
	}
	return ""
}

func (x *RunSummary) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *RunSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RunSummary) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *RunSummary) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *RunSummary) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RunLogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunLogRequest) Reset() {
	*x = RunLogRequest{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunLogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunLogRequest) ProtoMessage() {}

func (x *RunLogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunLogRequest.ProtoReflect.Descriptor instead.
func (*RunLogRequest) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *RunLogRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type RunLogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Run           *RunSummary            `protobuf:"bytes,1,opt,name=run,proto3" json:"run,omitempty"`
	Events        []*WorkflowEvent       `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunLogResponse) Reset() {
	*x = RunLogResponse{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunLogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunLogResponse) ProtoMessage() {}

func (x *RunLogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunLogResponse.ProtoReflect.Descriptor instead.
func (*RunLogResponse) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *RunLogResponse) GetRun() *RunSummary {
	if x != nil {
		return x.Run
	}
	return nil
}

func (x *RunLogResponse) GetEvents() []*WorkflowEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{13}
}

type ValidateSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *RuntimeSettings       `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSettingsRequest) Reset() {
	*x = ValidateSettingsRequest{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSettingsRequest) ProtoMessage() {}

func (x *ValidateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSettingsRequest.ProtoReflect.Descriptor instead.
func (*ValidateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{14}
}

func (x *ValidateSettingsRequest) GetSettings() *RuntimeSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type SettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *RuntimeSettings       `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	Checks        []*SettingsCheck       `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	Valid         bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsResponse) Reset() {
	*x = SettingsResponse{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsResponse) ProtoMessage() {}

func (x *SettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsResponse.ProtoReflect.Descriptor instead.
func (*SettingsResponse) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{15}
}

func (x *SettingsResponse) GetSettings() *RuntimeSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *SettingsResponse) GetChecks() []*SettingsCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *SettingsResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type SettingsValidationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      *RuntimeSettings       `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	Checks        []*SettingsCheck       `protobuf:"bytes,2,rep,name=checks,proto3" json:"checks,omitempty"`
	Valid         bool                   `protobuf:"varint,3,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsValidationResponse) Reset() {
	*x = SettingsValidationResponse{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsValidationResponse) ProtoMessage() {}

func (x *SettingsValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsValidationResponse.ProtoReflect.Descriptor instead.
func (*SettingsValidationResponse) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{16}
}

func (x *SettingsValidationResponse) GetSettings() *RuntimeSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *SettingsValidationResponse) GetChecks() []*SettingsCheck {
	if x != nil {
		return x.Checks
	}
	return nil
}

func (x *SettingsValidationResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

type RuntimeSettings struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RepoRoot          string                 `protobuf:"bytes,1,opt,name=repo_root,json=repoRoot,proto3" json:"repo_root,omitempty"`
	AppsConfigPath    string                 `protobuf:"bytes,2,opt,name=apps_config_path,json=appsConfigPath,proto3" json:"apps_config_path,omitempty"`
	SecretsConfigPath string                 `protobuf:"bytes,3,opt,name=secrets_config_path,json=secretsConfigPath,proto3" json:"secrets_config_path,omitempty"`
	GeneratedAppsPath string                 `protobuf:"bytes,4,opt,name=generated_apps_path,json=generatedAppsPath,proto3" json:"generated_apps_path,omitempty"`
	ArchiveRoot       string                 `protobuf:"bytes,5,opt,name=archive_root,json=archiveRoot,proto3" json:"archive_root,omitempty"`
	WorkflowDbPath    string                 `protobuf:"bytes,6,opt,name=workflow_db_path,json=workflowDbPath,proto3" json:"workflow_db_path,omitempty"`
	OpVault           string                 `protobuf:"bytes,7,opt,name=op_vault,json=opVault,proto3" json:"op_vault,omitempty"`
	OpItem            string                 `protobuf:"bytes,8,opt,name=op_item,json=opItem,proto3" json:"op_item,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RuntimeSettings) Reset() {
	*x = RuntimeSettings{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeSettings) ProtoMessage() {}

func (x *RuntimeSettings) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeSettings.ProtoReflect.Descriptor instead.
func (*RuntimeSettings) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{17}
}

func (x *RuntimeSettings) GetRepoRoot() string {
	if x != nil {
		return x.RepoRoot
	}
	return ""
}

func (x *RuntimeSettings) GetAppsConfigPath() string {
	if x != nil {
		return x.AppsConfigPath
	}
	return ""
}

func (x *RuntimeSettings) GetSecretsConfigPath() string {
	if x != nil {
		return x.SecretsConfigPath
	}
	return ""
}

func (x *RuntimeSettings) GetGeneratedAppsPath() string {
	if x != nil {
		return x.GeneratedAppsPath
	}
	return ""
}

func (x *RuntimeSettings) GetArchiveRoot() string {
	if x != nil {
		return x.ArchiveRoot
	}
	return ""
}

func (x *RuntimeSettings) GetWorkflowDbPath() string {
	if x != nil {
		return x.WorkflowDbPath
	}
	return ""
}

func (x *RuntimeSettings) GetOpVault() string {
	if x != nil {
		return x.OpVault
	}
	return ""
}

func (x *RuntimeSettings) GetOpItem() string {
	if x != nil {
		return x.OpItem
	}
	return ""
}

type SettingsCheck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Path          string                 `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsCheck) Reset() {
	*x = SettingsCheck{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsCheck) ProtoMessage() {}

func (x *SettingsCheck) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsCheck.ProtoReflect.Descriptor instead.
func (*SettingsCheck) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{18}
}

func (x *SettingsCheck) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SettingsCheck) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SettingsCheck) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SettingsCheck) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SettingsCheck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserPreferencesRequest) Reset() {
	*x = GetUserPreferencesRequest{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPreferencesRequest) ProtoMessage() {}

func (x *GetUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{19}
}

type SaveUserPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUserPreferencesRequest) Reset() {
	*x = SaveUserPreferencesRequest{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUserPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUserPreferencesRequest) ProtoMessage() {}

func (x *SaveUserPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUserPreferencesRequest.ProtoReflect.Descriptor instead.
func (*SaveUserPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{20}
}

func (x *SaveUserPreferencesRequest) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

type UserPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Theme         string                 `protobuf:"bytes,1,opt,name=theme,proto3" json:"theme,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPreferencesResponse) Reset() {
	*x = UserPreferencesResponse{}
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPreferencesResponse) ProtoMessage() {}

func (x *UserPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_packages_bridge_proto_workflow_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPreferencesResponse.ProtoReflect.Descriptor instead.
func (*UserPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_packages_bridge_proto_workflow_proto_rawDescGZIP(), []int{21}
}

func (x *UserPreferencesResponse) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

func (x *UserPreferencesResponse) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_packages_bridge_proto_workflow_proto protoreflect.FileDescriptor

const file_packages_bridge_proto_workflow_proto_rawDesc = "" +
	"\n" +
	"$packages/bridge/proto/workflow.proto\x12\x0fmacos.bridge.v1\"\x16\n" +
	"\x14ListWorkflowsRequest\"P\n" +
	"\x15ListWorkflowsResponse\x127\n" +
	"\tworkflows\x18\x01 \x03(\v2\x19.macos.bridge.v1.WorkflowR\tworkflows\"\xe4\x01\n" +
	"\bWorkflow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vchanges_mac\x18\x04 \x01(\tR\n" +
	"changesMac\x12.\n" +
	"\x06phases\x18\x05 \x03(\v2\x16.macos.bridge.v1.PhaseR\x06phases\x12A\n" +
	"\fconfirmation\x18\x06 \x01(\v2\x1d.macos.bridge.v1.ConfirmationR\fconfirmation\"E\n" +
	"\x05Phase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\"}\n" +
	"\fConfirmation\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12=\n" +
	"\aoptions\x18\x03 \x03(\v2#.macos.bridge.v1.ConfirmationOptionR\aoptions\"\xbc\x01\n" +
	"\x12ConfirmationOption\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcontinue\x18\x04 \x01(\bR\bcontinue\x12\x12\n" +
	"\x04back\x18\x05 \x01(\bR\x04back\x12.\n" +
	"\x06phases\x18\x06 \x03(\v2\x16.macos.bridge.v1.PhaseR\x06phases\"\x97\x01\n" +
	"\x12RunWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x124\n" +
	"\x16confirmation_option_id\x18\x02 \x01(\tR\x14confirmationOptionId\x12*\n" +
	"\x11enabled_phase_ids\x18\x03 \x03(\tR\x0fenabledPhaseIds\"\xe7\x01\n" +
	"\rWorkflowEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x19\n" +
	"\bphase_id\x18\x05 \x01(\tR\aphaseId\x12\x1d\n" +
	"\n" +
	"phase_name\x18\x06 \x01(\tR\tphaseName\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\b \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\"'\n" +
	"\x0fListRunsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\"C\n" +
	"\x10ListRunsResponse\x12/\n" +
	"\x04runs\x18\x01 \x03(\v2\x1b.macos.bridge.v1.RunSummaryR\x04runs\"\xe7\x02\n" +
	"\n" +
	"RunSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12#\n" +
	"\rworkflow_name\x18\x03 \x01(\tR\fworkflowName\x124\n" +
	"\x16confirmation_option_id\x18\x04 \x01(\tR\x14confirmationOptionId\x12:\n" +
	"\x19confirmation_option_label\x18\x05 \x01(\tR\x17confirmationOptionLabel\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\t \x01(\tR\vcompletedAt\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\"&\n" +
	"\rRunLogRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"w\n" +
	"\x0eRunLogResponse\x12-\n" +
	"\x03run\x18\x01 \x01(\v2\x1b.macos.bridge.v1.RunSummaryR\x03run\x126\n" +
	"\x06events\x18\x02 \x03(\v2\x1e.macos.bridge.v1.WorkflowEventR\x06events\"\x14\n" +
	"\x12GetSettingsRequest\"W\n" +
	"\x17ValidateSettingsRequest\x12<\n" +
	"\bsettings\x18\x01 \x01(\v2 .macos.bridge.v1.RuntimeSettingsR\bsettings\"\x9e\x01\n" +
	"\x10SettingsResponse\x12<\n" +
	"\bsettings\x18\x01 \x01(\v2 .macos.bridge.v1.RuntimeSettingsR\bsettings\x126\n" +
	"\x06checks\x18\x02 \x03(\v2\x1e.macos.bridge.v1.SettingsCheckR\x06checks\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\"\xa8\x01\n" +
	"\x1aSettingsValidationResponse\x12<\n" +
	"\bsettings\x18\x01 \x01(\v2 .macos.bridge.v1.RuntimeSettingsR\bsettings\x126\n" +
	"\x06checks\x18\x02 \x03(\v2\x1e.macos.bridge.v1.SettingsCheckR\x06checks\x12\x14\n" +
	"\x05valid\x18\x03 \x01(\bR\x05valid\"\xb9\x02\n" +
	"\x0fRuntimeSettings\x12\x1b\n" +
	"\trepo_root\x18\x01 \x01(\tR\brepoRoot\x12(\n" +
	"\x10apps_config_path\x18\x02 \x01(\tR\x0eappsConfigPath\x12.\n" +
	"\x13secrets_config_path\x18\x03 \x01(\tR\x11secretsConfigPath\x12.\n" +
	"\x13generated_apps_path\x18\x04 \x01(\tR\x11generatedAppsPath\x12!\n" +
	"\farchive_root\x18\x05 \x01(\tR\varchiveRoot\x12(\n" +
	"\x10workflow_db_path\x18\x06 \x01(\tR\x0eworkflowDbPath\x12\x19\n" +
	"\bop_vault\x18\a \x01(\tR\aopVault\x12\x17\n" +
	"\aop_item\x18\b \x01(\tR\x06opItem\"}\n" +
	"\rSettingsCheck\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x1b\n" +
	"\x19GetUserPreferencesRequest\"2\n" +
	"\x1aSaveUserPreferencesRequest\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\"N\n" +
	"\x17UserPreferencesResponse\x12\x14\n" +
	"\x05theme\x18\x01 \x01(\tR\x05theme\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\tR\tupdatedAt2\xfe\x05\n" +
	"\x0eWorkflowBridge\x12^\n" +
	"\rListWorkflows\x12%.macos.bridge.v1.ListWorkflowsRequest\x1a&.macos.bridge.v1.ListWorkflowsResponse\x12T\n" +
	"\vRunWorkflow\x12#.macos.bridge.v1.RunWorkflowRequest\x1a\x1e.macos.bridge.v1.WorkflowEvent0\x01\x12O\n" +
	"\bListRuns\x12 .macos.bridge.v1.ListRunsRequest\x1a!.macos.bridge.v1.ListRunsResponse\x12I\n" +
	"\x06RunLog\x12\x1e.macos.bridge.v1.RunLogRequest\x1a\x1f.macos.bridge.v1.RunLogResponse\x12U\n" +
	"\vGetSettings\x12#.macos.bridge.v1.GetSettingsRequest\x1a!.macos.bridge.v1.SettingsResponse\x12i\n" +
	"\x10ValidateSettings\x12(.macos.bridge.v1.ValidateSettingsRequest\x1a+.macos.bridge.v1.SettingsValidationResponse\x12j\n" +
	"\x12GetUserPreferences\x12*.macos.bridge.v1.GetUserPreferencesRequest\x1a(.macos.bridge.v1.UserPreferencesResponse\x12l\n" +
	"\x13SaveUserPreferences\x12+.macos.bridge.v1.SaveUserPreferencesRequest\x1a(.macos.bridge.v1.UserPreferencesResponseB-Z+github.com/gocanto/mac-os/internal/bridgepbb\x06proto3"

var (
	file_packages_bridge_proto_workflow_proto_rawDescOnce sync.Once
	file_packages_bridge_proto_workflow_proto_rawDescData []byte
)

func file_packages_bridge_proto_workflow_proto_rawDescGZIP() []byte {
	file_packages_bridge_proto_workflow_proto_rawDescOnce.Do(func() {
		file_packages_bridge_proto_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packages_bridge_proto_workflow_proto_rawDesc), len(file_packages_bridge_proto_workflow_proto_rawDesc)))
	})
	return file_packages_bridge_proto_workflow_proto_rawDescData
}

var file_packages_bridge_proto_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_packages_bridge_proto_workflow_proto_goTypes = []any{
	(*ListWorkflowsRequest)(nil),       // 0: macos.bridge.v1.ListWorkflowsRequest
	(*ListWorkflowsResponse)(nil),      // 1: macos.bridge.v1.ListWorkflowsResponse
	(*Workflow)(nil),                   // 2: macos.bridge.v1.Workflow
	(*Phase)(nil),                      // 3: macos.bridge.v1.Phase
	(*Confirmation)(nil),               // 4: macos.bridge.v1.Confirmation
	(*ConfirmationOption)(nil),         // 5: macos.bridge.v1.ConfirmationOption
	(*RunWorkflowRequest)(nil),         // 6: macos.bridge.v1.RunWorkflowRequest
	(*WorkflowEvent)(nil),              // 7: macos.bridge.v1.WorkflowEvent
	(*ListRunsRequest)(nil),            // 8: macos.bridge.v1.ListRunsRequest
	(*ListRunsResponse)(nil),           // 9: macos.bridge.v1.ListRunsResponse
	(*RunSummary)(nil),                 // 10: macos.bridge.v1.RunSummary
	(*RunLogRequest)(nil),              // 11: macos.bridge.v1.RunLogRequest
	(*RunLogResponse)(nil),             // 12: macos.bridge.v1.RunLogResponse
	(*GetSettingsRequest)(nil),         // 13: macos.bridge.v1.GetSettingsRequest
	(*ValidateSettingsRequest)(nil),    // 14: macos.bridge.v1.ValidateSettingsRequest
	(*SettingsResponse)(nil),           // 15: macos.bridge.v1.SettingsResponse
	(*SettingsValidationResponse)(nil), // 16: macos.bridge.v1.SettingsValidationResponse
	(*RuntimeSettings)(nil),            // 17: macos.bridge.v1.RuntimeSettings
	(*SettingsCheck)(nil),              // 18: macos.bridge.v1.SettingsCheck
	(*GetUserPreferencesRequest)(nil),  // 19: macos.bridge.v1.GetUserPreferencesRequest
	(*SaveUserPreferencesRequest)(nil), // 20: macos.bridge.v1.SaveUserPreferencesRequest
	(*UserPreferencesResponse)(nil),    // 21: macos.bridge.v1.UserPreferencesResponse
}
var file_packages_bridge_proto_workflow_proto_depIdxs = []int32{
	2,  // 0: macos.bridge.v1.ListWorkflowsResponse.workflows:type_name -> macos.bridge.v1.Workflow
	3,  // 1: macos.bridge.v1.Workflow.phases:type_name -> macos.bridge.v1.Phase
	4,  // 2: macos.bridge.v1.Workflow.confirmation:type_name -> macos.bridge.v1.Confirmation
	5,  // 3: macos.bridge.v1.Confirmation.options:type_name -> macos.bridge.v1.ConfirmationOption
	3,  // 4: macos.bridge.v1.ConfirmationOption.phases:type_name -> macos.bridge.v1.Phase
	10, // 5: macos.bridge.v1.ListRunsResponse.runs:type_name -> macos.bridge.v1.RunSummary
	10, // 6: macos.bridge.v1.RunLogResponse.run:type_name -> macos.bridge.v1.RunSummary
	7,  // 7: macos.bridge.v1.RunLogResponse.events:type_name -> macos.bridge.v1.WorkflowEvent
	17, // 8: macos.bridge.v1.ValidateSettingsRequest.settings:type_name -> macos.bridge.v1.RuntimeSettings
	17, // 9: macos.bridge.v1.SettingsResponse.settings:type_name -> macos.bridge.v1.RuntimeSettings
	18, // 10: macos.bridge.v1.SettingsResponse.checks:type_name -> macos.bridge.v1.SettingsCheck
	17, // 11: macos.bridge.v1.SettingsValidationResponse.settings:type_name -> macos.bridge.v1.RuntimeSettings
	18, // 12: macos.bridge.v1.SettingsValidationResponse.checks:type_name -> macos.bridge.v1.SettingsCheck
	0,  // 13: macos.bridge.v1.WorkflowBridge.ListWorkflows:input_type -> macos.bridge.v1.ListWorkflowsRequest
	6,  // 14: macos.bridge.v1.WorkflowBridge.RunWorkflow:input_type -> macos.bridge.v1.RunWorkflowRequest
	8,  // 15: macos.bridge.v1.WorkflowBridge.ListRuns:input_type -> macos.bridge.v1.ListRunsRequest
	11, // 16: macos.bridge.v1.WorkflowBridge.RunLog:input_type -> macos.bridge.v1.RunLogRequest
	13, // 17: macos.bridge.v1.WorkflowBridge.GetSettings:input_type -> macos.bridge.v1.GetSettingsRequest
	14, // 18: macos.bridge.v1.WorkflowBridge.ValidateSettings:input_type -> macos.bridge.v1.ValidateSettingsRequest
	19, // 19: macos.bridge.v1.WorkflowBridge.GetUserPreferences:input_type -> macos.bridge.v1.GetUserPreferencesRequest
	20, // 20: macos.bridge.v1.WorkflowBridge.SaveUserPreferences:input_type -> macos.bridge.v1.SaveUserPreferencesRequest
	1,  // 21: macos.bridge.v1.WorkflowBridge.ListWorkflows:output_type -> macos.bridge.v1.ListWorkflowsResponse
	7,  // 22: macos.bridge.v1.WorkflowBridge.RunWorkflow:output_type -> macos.bridge.v1.WorkflowEvent
	9,  // 23: macos.bridge.v1.WorkflowBridge.ListRuns:output_type -> macos.bridge.v1.ListRunsResponse
	12, // 24: macos.bridge.v1.WorkflowBridge.RunLog:output_type -> macos.bridge.v1.RunLogResponse
	15, // 25: macos.bridge.v1.WorkflowBridge.GetSettings:output_type -> macos.bridge.v1.SettingsResponse
	16, // 26: macos.bridge.v1.WorkflowBridge.ValidateSettings:output_type -> macos.bridge.v1.SettingsValidationResponse
	21, // 27: macos.bridge.v1.WorkflowBridge.GetUserPreferences:output_type -> macos.bridge.v1.UserPreferencesResponse
	21, // 28: macos.bridge.v1.WorkflowBridge.SaveUserPreferences:output_type -> macos.bridge.v1.UserPreferencesResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_packages_bridge_proto_workflow_proto_init() }
func file_packages_bridge_proto_workflow_proto_init() {
	if File_packages_bridge_proto_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packages_bridge_proto_workflow_proto_rawDesc), len(file_packages_bridge_proto_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_packages_bridge_proto_workflow_proto_goTypes,
		DependencyIndexes: file_packages_bridge_proto_workflow_proto_depIdxs,
		MessageInfos:      file_packages_bridge_proto_workflow_proto_msgTypes,
	}.Build()
	File_packages_bridge_proto_workflow_proto = out.File
	file_packages_bridge_proto_workflow_proto_goTypes = nil
	file_packages_bridge_proto_workflow_proto_depIdxs = nil
}
