name: Tests

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft || github.event.action == 'ready_for_review' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup workspace
        uses: ./.github/actions/setup-workspace

      - name: Build
        run: pnpm build

  test:
    name: Test
    runs-on: ubuntu-latest
    if: ${{ !github.event.pull_request.draft || github.event.action == 'ready_for_review' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup workspace
        uses: ./.github/actions/setup-workspace

      - name: Test
        run: pnpm test
